version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: nestjs-bookshelf-app
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGODB_DATABASE: "nestjs-bookshelf-app"
    networks:
      - nestjs

  nestjs-bookshelf-app:
    build: .
    container_name: nestjs-bookshelf-app
    restart: unless-stopped
    ports:
      - 8888:8080
    env_file:
      - .env
    networks:
      - nestjs

networks:
  nestjs:
    name: nestjs
